<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataFetcher.Domain_\**" />
    <EmbeddedResource Remove="DataFetcher.Domain_\**" />
    <None Remove="DataFetcher.Domain_\**" />
  </ItemGroup>

</Project>
